# NUMBER
<number> ::= <integer> | 
             <integer> "." <float_tail>    | 
             <integer> "e" <exponent_tail> |
             <integer> "." <float_tail> "e" <exponent_tail>


<exponent_tail> ::= "+" <digits> | "-" <digits>

<float_tail> ::= <digits>

<integer> ::= "+" <natural> | "-" <natural> | <natural>

<natural> ::= <nonzero> <digits> | <nonzero> "_" <digits> | <digit>

<digits> ::=  <digit> <digits> | <digit> "_" <digits> | <digit>

<digit> ::= <zero> | <nonzero> 

<zero> ::= "0" 

<nonzero> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"


# IDENTIFIER

<identifier> ::= <letter> | <letter> <alphanumerics>

<alphanumerics> ::= <alphanumeric> | <alphanumeric> <alphanumerics> | <alphanumeric> "_" <alphanumerics>

<alphanumeric> ::= <digit> | <letter>

<letter> ::= <lowercase_letter> | <uppercase_letter>

<digit> ::= <zero> | <nonzero> 

<zero> ::= "0" 

<nonzero> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<lowercase_letter> ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" 
		             | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" 

<uppercase_letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" 
                     | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"



# STRING

<inline_string> ::= "\"" <inline_string_chars>

<inline_string_chars> ::= <any_non_control_char> <inline_string_chars> | "\"" | "\\" <escape_sequence> <inline_string_chars>

<escape_sequence> ::= "\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t" | "u" <hex_digits>

<hex_digits> ::= <hex_digit> <hex_digit> <hex_digit> <hex_digit>

<hex_digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" |
                "A" | "B" | "C" | "D" | "E" | "F" |
                "a" | "b" | "c" | "d" | "e" | "f"

    

# MULTILINE STRING
