<number> ::= <float> | <integer> 

<float> ::= <integer> "." <digits>

<integer> ::= "+" <natural> | "-" <natural> | <natural>

<natural> ::= <nonzero> <digits> | <nonzero> "_" <digits> | <digit>

<digits> ::=  <digit> <digits> | <digit> "_" <digits> | <digit>

<digit> ::= <zero> | <nonzero> 

<zero> ::= "0" 

<nonzero> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
